
class DoneException(Exception):
    pass


class CancelException(Exception):
    pass
